# Generated by Django 3.0.6 on 2020-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(choices=[('CIC News', 'CIC News'), ('Canada.ca', 'Canada.ca')], default='CIC News', max_length=50),
        ),
    ]
