# Generated by Django 3.0.6 on 2020-11-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0002_auto_20201126_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
