# Generated by Django 3.1 on 2020-11-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
