# Generated by Django 3.1 on 2020-11-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_app', '0006_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
